_wandb:
    value:
        cli_version: 0.21.4
        e:
            zrji0uedjyfwd5trgd9vvasjf6l7xgcg:
                args:
                    - --lr=0.001
                    - --sim-start=0
                    - --sim-end=743
                    - --episodes=10
                    - --beta=0
                    - --gamma=1
                    - --wandb=on
                    - --wandb-project=TEST_DYNAMICS
                    - --dataset-name=CA_10_dynamics
                    - --wandb-run-name=CA_sac_lr=0.001_beta=0.0_gamma=1.0
                codePath: train_sac.py
                codePathLocal: train_sac.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1022755860480"
                        used: "781329006592"
                email: sabrina.savino@polito.it
                executable: c:\Users\sabry\Documents\Citylearn_dinamics\.venv\Scripts\python.exe
                git:
                    commit: b326e867efc3850c53cbaa4b2ae4cef7518b19c3
                    remote: https://github.com/SabSav/Citylearn_dinamics.git
                host: Sabrina
                memory:
                    total: "16456073216"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\sabry\Documents\Citylearn_dinamics\train_sac.py
                python: CPython 3.9.0
                root: C:\Users\sabry\Documents\Citylearn_dinamics
                startedAt: "2025-09-18T15:36:23.220076Z"
                writerId: zrji0uedjyfwd5trgd9vvasjf6l7xgcg
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.9.0
            "5": 0.21.4
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.4
            "13": windows-amd64
beta:
    value: 0
central_agent:
    value: false
data_dir:
    value: C:\Users\sabry\.citylearn\data
dataset:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\data\CA_10_dynamics\schema.json
dataset_mode:
    value: local
episodes:
    value: 10
gamma:
    value: 1
lr:
    value: 0.001
output_root:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\outputs
sim_end:
    value: 743
sim_start:
    value: 0
zip_path:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\outputs\CA_10_dynamics\save_models\sac\beta=0.0_gamma=1.0\lr=0.001\sac.zip
