_wandb:
    value:
        cli_version: 0.21.4
        e:
            atgq8ghzqvw5ag8wzyk91hegfojw487e:
                args:
                    - --wandb=on
                codePath: train_sac.py
                codePathLocal: train_sac.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1022755860480"
                        used: "801262268416"
                email: sabrina.savino@polito.it
                executable: c:\Users\sabry\Documents\Citylearn_dinamics\.venv\Scripts\python.exe
                host: Sabrina
                memory:
                    total: "16456073216"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\sabry\Documents\Citylearn_dinamics\train_sac.py
                python: CPython 3.9.0
                root: C:\Users\sabry\Documents\Citylearn_dinamics
                startedAt: "2025-09-16T14:34:25.783517Z"
                writerId: atgq8ghzqvw5ag8wzyk91hegfojw487e
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.9.0
            "5": 0.21.4
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.4
            "13": windows-amd64
beta:
    value: 0
central_agent:
    value: false
data_dir:
    value: C:\Users\sabry\.citylearn\data
dataset:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\data\TX_10_dynamics\schema.json
dataset_mode:
    value: path
episodes:
    value: 12
lr:
    value: 0.0003
output_root:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\outputs
sim_end:
    value: null
sim_start:
    value: null
zip_path:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\outputs\data\TX_10_dynamics\schema.json\save_models\sac\beta\lr\sac.zip
