_wandb:
    value:
        cli_version: 0.21.4
        e:
            9c725v9e67okqrvvfi9qyfe3bdqk58s1:
                args:
                    - --lr=0.001
                    - --episodes=10
                    - --sim-start=3624
                    - --sim-end=4343
                    - --wandb
                    - "on"
                    - --wandb-project
                    - TEST_DYNAMICS
                    - --beta=0
                    - --gamma=3.5
                    - --dhw-storage=21
                    - --electrical-storage=21
                    - --cooling-or-heating-device=21
                codePath: train_aac_madrl.py
                codePathLocal: train_aac_madrl.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1022755860480"
                        used: "780854095872"
                email: sabrina.savino@polito.it
                executable: c:\Users\sabry\Documents\Citylearn_dinamics\.venv\Scripts\python.exe
                git:
                    commit: b326e867efc3850c53cbaa4b2ae4cef7518b19c3
                    remote: https://github.com/SabSav/Citylearn_dinamics.git
                host: Sabrina
                memory:
                    total: "16456073216"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\sabry\Documents\Citylearn_dinamics\train_aac_madrl.py
                python: CPython 3.9.0
                root: C:\Users\sabry\Documents\Citylearn_dinamics
                startedAt: "2025-09-18T16:59:59.364885Z"
                writerId: 9c725v9e67okqrvvfi9qyfe3bdqk58s1
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.0
            "5": 0.21.4
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.4
            "13": windows-amd64
beta:
    value: 0
central_agent:
    value: false
classes:
    value:
        cooling_or_heating_device: 21
        dhw_storage: 21
        electrical_storage: 21
data_dir:
    value: C:\Users\sabry\.citylearn\data
dataset:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\data\TX_10_dynamics\schema.json
dataset_mode:
    value: path
episodes:
    value: 10
lr:
    value: 0.001
output_root:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\outputs
sim_end:
    value: 4343
sim_start:
    value: 3624
zip_path:
    value: C:\Users\sabry\Documents\Citylearn_dinamics\outputs\data\TX_10_dynamics\schema.json\save_models\aac_madrl\beta=0.0_gamma=3.5\lr=0.001\aac_madrl.zip
